name = "echo-crm"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "echo-crm"
database_id = "d92784a9-9674-4e0e-ac1a-4b5d399d4b9a"

[[kv_namespaces]]
binding = "CACHE"
id = "c068eb9d1547447b9a27485a6e25db6a"

[[services]]
binding = "ENGINE_RUNTIME"
service = "echo-engine-runtime"

[[services]]
binding = "SHARED_BRAIN"
service = "echo-shared-brain"

[triggers]
crons = ["0 8 * * MON"]
